from lyra.translator.types import Collection
from dataclasses import dataclass
from typing import Dict, Callable

from .collection_sis_energy_derived_projections import Collection_sis_energy_derived_projections
from .collection_satellite_lake_water_level import Collection_satellite_lake_water_level
from .collection_satellite_lake_water_temperature import Collection_satellite_lake_water_temperature
from .collection_multi_origin_c3s_atlas import Collection_multi_origin_c3s_atlas
from .collection_seasonal_postprocessed_single_levels import Collection_seasonal_postprocessed_single_levels
from .collection_satellite_ice_sheet_mass_balance import Collection_satellite_ice_sheet_mass_balance
from .collection_satellite_soil_moisture import Collection_satellite_soil_moisture
from .collection_insitu_gridded_observations_alpine_precipitation import Collection_insitu_gridded_observations_alpine_precipitation
from .collection_reanalysis_cerra_model_levels import Collection_reanalysis_cerra_model_levels
from .collection_reanalysis_uerra_europe_single_levels import Collection_reanalysis_uerra_europe_single_levels
from .collection_insitu_observations_near_surface_temperature_us_climate_reference_network import Collection_insitu_observations_near_surface_temperature_us_climate_reference_network
from .collection_seasonal_original_pressure_levels import Collection_seasonal_original_pressure_levels
from .collection_satellite_albedo import Collection_satellite_albedo
from .collection_satellite_upper_troposphere_humidity import Collection_satellite_upper_troposphere_humidity
from .collection_projections_cordex_domains_single_levels import Collection_projections_cordex_domains_single_levels
from .collection_sis_health_vector import Collection_sis_health_vector
from .collection_reanalysis_cerra_pressure_levels import Collection_reanalysis_cerra_pressure_levels
from .collection_sis_marine_properties import Collection_sis_marine_properties
from .collection_reanalysis_uerra_europe_soil_levels import Collection_reanalysis_uerra_europe_soil_levels
from .collection_sis_biodiversity_era5_regional import Collection_sis_biodiversity_era5_regional
from .collection_sis_hydrology_variables_derived_seasonal_reforecast import Collection_sis_hydrology_variables_derived_seasonal_reforecast
from .collection_reanalysis_era5_single_levels import Collection_reanalysis_era5_single_levels
from .collection_sis_energy_derived_reanalysis import Collection_sis_energy_derived_reanalysis
from .collection_satellite_sea_level_global import Collection_satellite_sea_level_global
from .collection_satellite_sea_surface_temperature_ensemble_product import Collection_satellite_sea_surface_temperature_ensemble_product
from .collection_reanalysis_carra_height_levels import Collection_reanalysis_carra_height_levels
from .collection_derived_era5_land_daily_statistics import Collection_derived_era5_land_daily_statistics
from .collection_insitu_observations_woudc_ozone_total_column_and_profiles import Collection_insitu_observations_woudc_ozone_total_column_and_profiles
from .collection_insitu_glaciers_extent import Collection_insitu_glaciers_extent
from .collection_projections_cmip5_daily_pressure_levels import Collection_projections_cmip5_daily_pressure_levels
from .collection_satellite_fire_burned_area import Collection_satellite_fire_burned_area
from .collection_reanalysis_uerra_europe_pressure_levels import Collection_reanalysis_uerra_europe_pressure_levels
from .collection_satellite_sea_ice_edge_type import Collection_satellite_sea_ice_edge_type
from .collection_sis_ocean_wave_timeseries import Collection_sis_ocean_wave_timeseries
from .collection_satellite_cloud_properties import Collection_satellite_cloud_properties
from .collection_seasonal_postprocessed_pressure_levels import Collection_seasonal_postprocessed_pressure_levels
from .collection_sis_heat_and_cold_spells import Collection_sis_heat_and_cold_spells
from .collection_derived_gridded_glacier_mass_change import Collection_derived_gridded_glacier_mass_change
from .collection_reanalysis_cerra_land import Collection_reanalysis_cerra_land
from .collection_satellite_sea_surface_temperature import Collection_satellite_sea_surface_temperature
from .collection_reanalysis_uerra_europe_height_levels import Collection_reanalysis_uerra_europe_height_levels
from .collection_reanalysis_era5_land import Collection_reanalysis_era5_land
from .collection_reanalysis_carra_single_levels import Collection_reanalysis_carra_single_levels
from .collection_sis_biodiversity_cmip5_regional import Collection_sis_biodiversity_cmip5_regional
from .collection_insitu_gridded_observations_global_and_regional import Collection_insitu_gridded_observations_global_and_regional
from .collection_projections_cmip5_daily_single_levels import Collection_projections_cmip5_daily_single_levels
from .collection_sis_biodiversity_era5_global import Collection_sis_biodiversity_era5_global
from .collection_reanalysis_era5_land_monthly_means import Collection_reanalysis_era5_land_monthly_means
from .collection_insitu_comprehensive_upper_air_observation_network import Collection_insitu_comprehensive_upper_air_observation_network
from .collection_projections_cmip6 import Collection_projections_cmip6
from .collection_insitu_observations_gruan_reference_network import Collection_insitu_observations_gruan_reference_network
from .collection_insitu_gridded_observations_europe import Collection_insitu_gridded_observations_europe
from .collection_derived_era5_pressure_levels_daily_statistics import Collection_derived_era5_pressure_levels_daily_statistics
from .collection_reanalysis_era5_complete import Collection_reanalysis_era5_complete
from .collection_derived_near_surface_meteorological_variables import Collection_derived_near_surface_meteorological_variables
from .collection_sis_tourism_snow_indicators import Collection_sis_tourism_snow_indicators
from .collection_reanalysis_uerra_europe_complete import Collection_reanalysis_uerra_europe_complete
from .collection_sis_european_risk_extreme_precipitation_indicators import Collection_sis_european_risk_extreme_precipitation_indicators
from .collection_satellite_total_column_water_vapour_land_ocean import Collection_satellite_total_column_water_vapour_land_ocean
from .collection_sis_temperature_statistics import Collection_sis_temperature_statistics
from .collection_satellite_fire_radiative_power import Collection_satellite_fire_radiative_power
from .collection_satellite_methane import Collection_satellite_methane
from .collection_satellite_ice_sheet_elevation_change import Collection_satellite_ice_sheet_elevation_change
from .collection_seasonal_monthly_pressure_levels import Collection_seasonal_monthly_pressure_levels
from .collection_satellite_carbon_dioxide import Collection_satellite_carbon_dioxide
from .collection_insitu_observations_surface_land import Collection_insitu_observations_surface_land
from .collection_projections_cmip5_monthly_single_levels import Collection_projections_cmip5_monthly_single_levels
from .collection_insitu_observations_surface_marine import Collection_insitu_observations_surface_marine
from .collection_seasonal_monthly_ocean import Collection_seasonal_monthly_ocean
from .collection_seasonal_monthly_single_levels import Collection_seasonal_monthly_single_levels
from .collection_satellite_greenland_ice_sheet_velocity import Collection_satellite_greenland_ice_sheet_velocity
from .collection_satellite_ozone_v1 import Collection_satellite_ozone_v1
from .collection_derived_era5_single_levels_daily_statistics import Collection_derived_era5_single_levels_daily_statistics
from .collection_seasonal_original_single_levels import Collection_seasonal_original_single_levels
from .collection_reanalysis_cerra_single_levels import Collection_reanalysis_cerra_single_levels
from .collection_satellite_precipitation_microwave import Collection_satellite_precipitation_microwave
from .collection_sis_ocean_wave_indicators import Collection_sis_ocean_wave_indicators
from .collection_sis_european_wind_storm_synthetic_events import Collection_sis_european_wind_storm_synthetic_events
from .collection_reanalysis_era5_single_levels_monthly_means import Collection_reanalysis_era5_single_levels_monthly_means
from .collection_reanalysis_cerra_height_levels import Collection_reanalysis_cerra_height_levels
from .collection_sis_agroproductivity_indicators import Collection_sis_agroproductivity_indicators
from .collection_derived_reanalysis_energy_moisture_budget import Collection_derived_reanalysis_energy_moisture_budget
from .collection_sis_hydrology_variables_derived_projections import Collection_sis_hydrology_variables_derived_projections
from .collection_reanalysis_carra_model_levels import Collection_reanalysis_carra_model_levels
from .collection_projections_cmip6_decadal_prototype import Collection_projections_cmip6_decadal_prototype
from .collection_sis_ecv_cmip5_bias_corrected import Collection_sis_ecv_cmip5_bias_corrected
from .collection_satellite_surface_radiation_budget import Collection_satellite_surface_radiation_budget
from .collection_satellite_sea_ice_thickness import Collection_satellite_sea_ice_thickness
from .collection_sis_extreme_indices_cmip6 import Collection_sis_extreme_indices_cmip6
from .collection_satellite_aerosol_properties import Collection_satellite_aerosol_properties
from .collection_insitu_observations_igra_baseline_network import Collection_insitu_observations_igra_baseline_network
from .collection_satellite_ocean_colour import Collection_satellite_ocean_colour
from .collection_reanalysis_oras5 import Collection_reanalysis_oras5
from .collection_sis_european_wind_storm_indicators import Collection_sis_european_wind_storm_indicators
from .collection_satellite_earth_radiation_budget import Collection_satellite_earth_radiation_budget
from .collection_sis_hydrology_variables_derived_seasonal_forecast import Collection_sis_hydrology_variables_derived_seasonal_forecast
from .collection_ecv_for_climate_change import Collection_ecv_for_climate_change
from .collection_sis_energy_pecd import Collection_sis_energy_pecd
from .collection_satellite_sea_ice_concentration import Collection_satellite_sea_ice_concentration
from .collection_derived_utci_historical import Collection_derived_utci_historical
from .collection_sis_water_level_change_timeseries_cmip6 import Collection_sis_water_level_change_timeseries_cmip6
from .collection_satellite_lai_fapar import Collection_satellite_lai_fapar
from .collection_satellite_land_cover import Collection_satellite_land_cover
from .collection_satellite_total_column_water_vapour_ocean import Collection_satellite_total_column_water_vapour_ocean
from .collection_projections_cmip5_monthly_pressure_levels import Collection_projections_cmip5_monthly_pressure_levels
from .collection_sis_hydrology_meteorology_derived_projections import Collection_sis_hydrology_meteorology_derived_projections
from .collection_sis_water_level_change_indicators_cmip6 import Collection_sis_water_level_change_indicators_cmip6
from .collection_sis_agroclimatic_indicators import Collection_sis_agroclimatic_indicators
from .collection_projections_climate_atlas import Collection_projections_climate_atlas
from .collection_reanalysis_carra_pressure_levels import Collection_reanalysis_carra_pressure_levels
from .collection_sis_biodiversity_cmip5_global import Collection_sis_biodiversity_cmip5_global
from .collection_insitu_gridded_observations_nordic import Collection_insitu_gridded_observations_nordic
from .collection_reanalysis_era5_pressure_levels_monthly_means import Collection_reanalysis_era5_pressure_levels_monthly_means
from .collection_satellite_precipitation import Collection_satellite_precipitation
from .collection_insitu_observations_gnss import Collection_insitu_observations_gnss
from .collection_sis_agrometeorological_indicators import Collection_sis_agrometeorological_indicators
from .collection_sis_tourism_fire_danger_indicators import Collection_sis_tourism_fire_danger_indicators
from .collection_sis_ecde_climate_indicators import Collection_sis_ecde_climate_indicators
from .collection_satellite_humidity_profiles import Collection_satellite_humidity_profiles
from .collection_reanalysis_era5_pressure_levels import Collection_reanalysis_era5_pressure_levels

sis_energy_derived_projections = Collection_sis_energy_derived_projections
satellite_lake_water_level = Collection_satellite_lake_water_level
satellite_lake_water_temperature = Collection_satellite_lake_water_temperature
multi_origin_c3s_atlas = Collection_multi_origin_c3s_atlas
seasonal_postprocessed_single_levels = Collection_seasonal_postprocessed_single_levels
satellite_ice_sheet_mass_balance = Collection_satellite_ice_sheet_mass_balance
satellite_soil_moisture = Collection_satellite_soil_moisture
insitu_gridded_observations_alpine_precipitation = Collection_insitu_gridded_observations_alpine_precipitation
reanalysis_cerra_model_levels = Collection_reanalysis_cerra_model_levels
reanalysis_uerra_europe_single_levels = Collection_reanalysis_uerra_europe_single_levels
insitu_observations_near_surface_temperature_us_climate_reference_network = Collection_insitu_observations_near_surface_temperature_us_climate_reference_network
seasonal_original_pressure_levels = Collection_seasonal_original_pressure_levels
satellite_albedo = Collection_satellite_albedo
satellite_upper_troposphere_humidity = Collection_satellite_upper_troposphere_humidity
projections_cordex_domains_single_levels = Collection_projections_cordex_domains_single_levels
sis_health_vector = Collection_sis_health_vector
reanalysis_cerra_pressure_levels = Collection_reanalysis_cerra_pressure_levels
sis_marine_properties = Collection_sis_marine_properties
reanalysis_uerra_europe_soil_levels = Collection_reanalysis_uerra_europe_soil_levels
sis_biodiversity_era5_regional = Collection_sis_biodiversity_era5_regional
sis_hydrology_variables_derived_seasonal_reforecast = Collection_sis_hydrology_variables_derived_seasonal_reforecast
reanalysis_era5_single_levels = Collection_reanalysis_era5_single_levels
sis_energy_derived_reanalysis = Collection_sis_energy_derived_reanalysis
satellite_sea_level_global = Collection_satellite_sea_level_global
satellite_sea_surface_temperature_ensemble_product = Collection_satellite_sea_surface_temperature_ensemble_product
reanalysis_carra_height_levels = Collection_reanalysis_carra_height_levels
derived_era5_land_daily_statistics = Collection_derived_era5_land_daily_statistics
insitu_observations_woudc_ozone_total_column_and_profiles = Collection_insitu_observations_woudc_ozone_total_column_and_profiles
insitu_glaciers_extent = Collection_insitu_glaciers_extent
projections_cmip5_daily_pressure_levels = Collection_projections_cmip5_daily_pressure_levels
satellite_fire_burned_area = Collection_satellite_fire_burned_area
reanalysis_uerra_europe_pressure_levels = Collection_reanalysis_uerra_europe_pressure_levels
satellite_sea_ice_edge_type = Collection_satellite_sea_ice_edge_type
sis_ocean_wave_timeseries = Collection_sis_ocean_wave_timeseries
satellite_cloud_properties = Collection_satellite_cloud_properties
seasonal_postprocessed_pressure_levels = Collection_seasonal_postprocessed_pressure_levels
sis_heat_and_cold_spells = Collection_sis_heat_and_cold_spells
derived_gridded_glacier_mass_change = Collection_derived_gridded_glacier_mass_change
reanalysis_cerra_land = Collection_reanalysis_cerra_land
satellite_sea_surface_temperature = Collection_satellite_sea_surface_temperature
reanalysis_uerra_europe_height_levels = Collection_reanalysis_uerra_europe_height_levels
reanalysis_era5_land = Collection_reanalysis_era5_land
reanalysis_carra_single_levels = Collection_reanalysis_carra_single_levels
sis_biodiversity_cmip5_regional = Collection_sis_biodiversity_cmip5_regional
insitu_gridded_observations_global_and_regional = Collection_insitu_gridded_observations_global_and_regional
projections_cmip5_daily_single_levels = Collection_projections_cmip5_daily_single_levels
sis_biodiversity_era5_global = Collection_sis_biodiversity_era5_global
reanalysis_era5_land_monthly_means = Collection_reanalysis_era5_land_monthly_means
insitu_comprehensive_upper_air_observation_network = Collection_insitu_comprehensive_upper_air_observation_network
projections_cmip6 = Collection_projections_cmip6
insitu_observations_gruan_reference_network = Collection_insitu_observations_gruan_reference_network
insitu_gridded_observations_europe = Collection_insitu_gridded_observations_europe
derived_era5_pressure_levels_daily_statistics = Collection_derived_era5_pressure_levels_daily_statistics
reanalysis_era5_complete = Collection_reanalysis_era5_complete
derived_near_surface_meteorological_variables = Collection_derived_near_surface_meteorological_variables
sis_tourism_snow_indicators = Collection_sis_tourism_snow_indicators
reanalysis_uerra_europe_complete = Collection_reanalysis_uerra_europe_complete
sis_european_risk_extreme_precipitation_indicators = Collection_sis_european_risk_extreme_precipitation_indicators
satellite_total_column_water_vapour_land_ocean = Collection_satellite_total_column_water_vapour_land_ocean
sis_temperature_statistics = Collection_sis_temperature_statistics
satellite_fire_radiative_power = Collection_satellite_fire_radiative_power
satellite_methane = Collection_satellite_methane
satellite_ice_sheet_elevation_change = Collection_satellite_ice_sheet_elevation_change
seasonal_monthly_pressure_levels = Collection_seasonal_monthly_pressure_levels
satellite_carbon_dioxide = Collection_satellite_carbon_dioxide
insitu_observations_surface_land = Collection_insitu_observations_surface_land
projections_cmip5_monthly_single_levels = Collection_projections_cmip5_monthly_single_levels
insitu_observations_surface_marine = Collection_insitu_observations_surface_marine
seasonal_monthly_ocean = Collection_seasonal_monthly_ocean
seasonal_monthly_single_levels = Collection_seasonal_monthly_single_levels
satellite_greenland_ice_sheet_velocity = Collection_satellite_greenland_ice_sheet_velocity
satellite_ozone_v1 = Collection_satellite_ozone_v1
derived_era5_single_levels_daily_statistics = Collection_derived_era5_single_levels_daily_statistics
seasonal_original_single_levels = Collection_seasonal_original_single_levels
reanalysis_cerra_single_levels = Collection_reanalysis_cerra_single_levels
satellite_precipitation_microwave = Collection_satellite_precipitation_microwave
sis_ocean_wave_indicators = Collection_sis_ocean_wave_indicators
sis_european_wind_storm_synthetic_events = Collection_sis_european_wind_storm_synthetic_events
reanalysis_era5_single_levels_monthly_means = Collection_reanalysis_era5_single_levels_monthly_means
reanalysis_cerra_height_levels = Collection_reanalysis_cerra_height_levels
sis_agroproductivity_indicators = Collection_sis_agroproductivity_indicators
derived_reanalysis_energy_moisture_budget = Collection_derived_reanalysis_energy_moisture_budget
sis_hydrology_variables_derived_projections = Collection_sis_hydrology_variables_derived_projections
reanalysis_carra_model_levels = Collection_reanalysis_carra_model_levels
projections_cmip6_decadal_prototype = Collection_projections_cmip6_decadal_prototype
sis_ecv_cmip5_bias_corrected = Collection_sis_ecv_cmip5_bias_corrected
satellite_surface_radiation_budget = Collection_satellite_surface_radiation_budget
satellite_sea_ice_thickness = Collection_satellite_sea_ice_thickness
sis_extreme_indices_cmip6 = Collection_sis_extreme_indices_cmip6
satellite_aerosol_properties = Collection_satellite_aerosol_properties
insitu_observations_igra_baseline_network = Collection_insitu_observations_igra_baseline_network
satellite_ocean_colour = Collection_satellite_ocean_colour
reanalysis_oras5 = Collection_reanalysis_oras5
sis_european_wind_storm_indicators = Collection_sis_european_wind_storm_indicators
satellite_earth_radiation_budget = Collection_satellite_earth_radiation_budget
sis_hydrology_variables_derived_seasonal_forecast = Collection_sis_hydrology_variables_derived_seasonal_forecast
ecv_for_climate_change = Collection_ecv_for_climate_change
sis_energy_pecd = Collection_sis_energy_pecd
satellite_sea_ice_concentration = Collection_satellite_sea_ice_concentration
derived_utci_historical = Collection_derived_utci_historical
sis_water_level_change_timeseries_cmip6 = Collection_sis_water_level_change_timeseries_cmip6
satellite_lai_fapar = Collection_satellite_lai_fapar
satellite_land_cover = Collection_satellite_land_cover
satellite_total_column_water_vapour_ocean = Collection_satellite_total_column_water_vapour_ocean
projections_cmip5_monthly_pressure_levels = Collection_projections_cmip5_monthly_pressure_levels
sis_hydrology_meteorology_derived_projections = Collection_sis_hydrology_meteorology_derived_projections
sis_water_level_change_indicators_cmip6 = Collection_sis_water_level_change_indicators_cmip6
sis_agroclimatic_indicators = Collection_sis_agroclimatic_indicators
projections_climate_atlas = Collection_projections_climate_atlas
reanalysis_carra_pressure_levels = Collection_reanalysis_carra_pressure_levels
sis_biodiversity_cmip5_global = Collection_sis_biodiversity_cmip5_global
insitu_gridded_observations_nordic = Collection_insitu_gridded_observations_nordic
reanalysis_era5_pressure_levels_monthly_means = Collection_reanalysis_era5_pressure_levels_monthly_means
satellite_precipitation = Collection_satellite_precipitation
insitu_observations_gnss = Collection_insitu_observations_gnss
sis_agrometeorological_indicators = Collection_sis_agrometeorological_indicators
sis_tourism_fire_danger_indicators = Collection_sis_tourism_fire_danger_indicators
sis_ecde_climate_indicators = Collection_sis_ecde_climate_indicators
satellite_humidity_profiles = Collection_satellite_humidity_profiles
reanalysis_era5_pressure_levels = Collection_reanalysis_era5_pressure_levels
